### ISSUE TITLE
Compatibility with older versions of node

### ISSUE THREAD

**Issue by midknight41** [hapijs/code#107]
Hi Folks,

Can you confirm that you've intentionally dropped support for node.js 4 and 6? If so that does seem a bit harsh. I mean, version 8 isn't even under LTS yet.

Any users of code won't be able to upgrade and still offer compatibility with older versions of node as all our tests break.

**Comment by cjihrig** [comment]
There is an effort in hapi core to move completely to async/await. Unfortunately, that does involve dropping support for older versions of Node. To answer your question, yes, that was intentional. You can continue using the older versions of `code`. The module doesn't change much/often, so you should be fine.

**Comment by CodisRedding** [comment]
Which version of Code introduced async so that I can rollback to the previous one?

**Comment by cjihrig** [comment]
v5.0.0 introduced async functions.
