### ISSUE TITLE
Convenient way to add methods.

### ISSUE THREAD

**Issue by coder13** [hapijs/code#41]
Unless I'm completely unaware of a simple way to do this, this should be possible just like it is in chai. It's as simple as exposing `internals.addMethod`.

I bypassed it by modifying the prototype of expect() (`expect().__proto__`).
but then you have to actually pass in a value to expect() and complete a assertion for lab to not complain.

My full solution was:
```js
let t = expect(2);
t.__proto__.objMatch = function (value) {
	return this.__proto__.assert.call(this, isMatch(this._ref, value));
};
t.to.equal(2);
```

An extremely ugly solution but it works.

**Comment by hueniverse** [comment]
"should be possible just like it is in chai" - why not just use chai? Not everything should be extended.

**Comment by coder13** [comment]
Why shouldn't everything be able to be extended? That puts power in the hands of the developer and they can continue to use simple, yet powerful libraries. Being able to plug many simple libraries together to make exactly what one needs is far superior than having to use a few things from large libraries.

I'm using code because of it's simplicity but the fact that it can't be extended (which is as simple as exposing a single function) is something I feel is missing from this simple library.

**Comment by hueniverse** [comment]
Because once you allow extensions you need to maintain that API and in many cases, that will limit your ability to make internal changes. It's a long-term PITA. I belong to the No First school of open source leadership.

**Comment by cjihrig** [comment]
I'm going to close this for now, in the same spirit as #39. If anyone can convince @hueniverse that this is a good idea, then we can revisit :-)

**Comment by dpmott** [comment]
(This comment is intended to detail a full work-around example and the issues with it, and is not intended to be a call to action.)

I would also enjoy the ability to extend Hapi Code to support a custom matcher. Unfortunately, in a typescript project I'm not sure how the @types/code definitions could be made to allow for a _seamless_ use scenario.

Based on the example that @coder13 offered in their OP, I coded up what this might look like using Hapi Lab 18.0.1 / Hapi Code 5.2.4:

```
Object.getPrototypeOf(expect(null)).uuid = function () {
  const isUuid = (input: string) => {
    const regex = new RegExp('^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$', 'i');
    return regex.test(input);
  };

  // tslint:disable-next-line: no-invalid-this
  return Object.getPrototypeOf(this).assert.call(this, isUuid(this._ref));
};

export interface ExtendedValues<T> extends AssertionChain<T> {
  uuid(): AssertionChain<T>;
}

// later, in a test: this generates a warning: Property 'uuid' does not exist on type 'AssertionChain<any>'.
  expect('my guid').to.be.a.uuid();

// fixing with a typecast
    (expect('my guid').to.be.a as ExtendedValues<string>).uuid();

// or, if you're okay with casting as 'any':
    (expect('my guid').to.be.a any).uuid();

// or you could just tell Typescript to shut up about it:
  // @ts-ignore: uuid() extension
  expect('my guid').to.be.a.uuid();
```

Note: Replaced the use of deprecated `__proto__` with `Object.getPrototypeOf`.

The real ugliness is that the grammar is typed, and knows what methods can follow, which would exclude anything layered into the `internals.Assertion` prototype because all of the types are implemented separately in `@types/code`.
