### ISSUE TITLE
Strange behavior of the 'include' assertion on a string value.

### ISSUE THREAD

**Issue by valdemon** [hapijs/code#97]
Hi,

```javascript
// Following fails and outputs: "Expected 'bc b' to include [ 'b', 'bc' ]"
Code.expect('bc b').to.include(['b', 'bc']);
```

When the `include` parameter array order is reversed the assertion succeeds, of course ;) 
Tested with the `v4.0.0`.
Is it a bug or a feature?

**Comment by cjihrig** [comment]
I think this is working as expected. `include()` does all of it's work via [`Hoek.contain()`](https://github.com/hapijs/hoek/blob/master/API.md#containref-values-options). The documentation for that method says:

> Note: comparing a string to overlapping values will result in failed comparison (e.g. contain('abc', ['ab', 'bc'])).

I think you're running into this situation. I'm going to close this, as I don't think it's an issue, but can reopen if we decide otherwise.

cc: @nlf who maintains hoek and may have something to add.

**Comment by valdemon** [comment]
Ok, thanks for the info, also noticed that about the `Hoek.contain()` in a meantime.
This simple overlapping example data (`ab bc` and similar) look quite innocent and not so destructive, so I understand your point.
In a real life test cases it can really fool you though..
At least one must always bear this feature in mind, when constructing assertions.

Thanks for a quick answer!

**Comment by cjihrig** [comment]
No problem. To be honest, I really dislike `include()` a lot. I think it tries to do too many things at once. I would only recommend using it for really simple things.

**Comment by valdemon** [comment]
Maybe it would be reasonable to put the link to the [Hoek.contain()](https://github.com/hapijs/hoek/blob/master/API.md#containref-values-options) doc (or the note from there) to the  [Code.include](https://github.com/hapijs/code/blob/master/API.md#includevalues) doc, just to avoid confusion?
